{% set name = "alembic" %}
{% set version = "1.8.1" %}
{% set hash = "cd0b5e45b14b706426b833f06369b9a6d5ee03f826ec3238723ce8caaf6e5ffa" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - alembic = alembic.config:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - mako
    - sqlalchemy >=1.3.0
    # Keeping noarch: python for now but may need to constrain these 2 as upstream
    # https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.7.0
    # These packages are needed for python <3.9
    - importlib-metadata
    - importlib_resources
    # Optional dependencies
    - python-dateutil

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  requires:
    - pip
    - python
    - pytest
  commands:
    - alembic --help
    - pip check

about:
  home: https://github.com/sqlalchemy/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: https://alembic.sqlalchemy.org/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
