{% set name = "alembic" %}
{% set version = "0.9.4" %}
{% set hash_type = "sha256" %}
{% set hash = "aa07406e74b18583c92c909b319bd79b89f281c2161615b0a11e2001df45a8d1" %}
{% set bundle = "tar.gz" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - alembic = alembic.config:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sqlalchemy >=0.7.6
    - mako
    - python-editor >=0.3
    - python-dateutil

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util

  commands:
    - alembic --help

about:
  home: https://bitbucket.org/zzzeek/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'A database migration tool for SQLAlchemy.'
  dev_url: https://bitbucket.org/zzzeek/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
