{% set name = "alembic" %}
{% set version = "1.13.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 203503117415561e203aa14541740643a611f641517f0209fcae63e9fa09f1a2

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - alembic = alembic.config:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - mako
    - sqlalchemy >=1.3.0
    - importlib-metadata  # [py<39]
    - importlib_resources  # [py<39]
    - typing-extensions >=4

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  requires:
    - pip
  commands:
    - alembic --help
    - pip check

about:
  home: https://github.com/sqlalchemy/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  description: Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python.
  dev_url: https://github.com/sqlalchemy/alembic

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
