{%set name = "alembic" %}
{%set version = "0.8.10" %}
{%set hash_type = "sha256" %}
{%set hash_val = "0e3b50e96218283ec7443fb661199f5a81f5879f766967a8a2d25e8f9d4e7919" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - alembic = alembic.config:main

  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sqlalchemy >=0.7.6
    - mako
    - python-editor >=0.3

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util

  commands:
    - alembic --help

about:
  home: http://bitbucket.org/zzzeek/alembic
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A database migration tool for SQLAlchemy.'
  dev_url: http://bitbucket.org/zzzeek/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
