{% set name = "alembic" %}
{% set version = "1.16.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: efab6ada0dd0fae2c92060800e0bf5c1dc26af15a10e02fb4babff164b4725e2

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - alembic = alembic.config:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
  run:
    - python
    - mako
    - sqlalchemy >=1.4.0
    - typing-extensions >=4.12
    - tomli  # [py<311]
    - typing_extensions >=4.12

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.autogenerate.compare
    - alembic.config
    - alembic.ddl
    - alembic.environment
    - alembic.migration
    - alembic.operations
    - alembic.operations.batch
    - alembic.runtime.migration
    - alembic.script
    - alembic.script.revision
    - alembic.util
    - alembic.util.messaging
    - alembic.util.sqla_compat
  requires:
    - pip
  commands:
    - pip check
    - alembic --help
    # Upstream tests based on database connection

about:
  home: https://alembic.sqlalchemy.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  description: Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: https://alembic.sqlalchemy.org

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar