{% set name = "alembic" %}
{% set version = "1.16.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43d37ba24b3d17bc1eb1024fe0f51cd1dc95aeb5464594a02c6bb9ca9864bfa4

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - alembic = alembic.config:main

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - wheel
  run:
    - python
    - mako
    - sqlalchemy >=1.4.0
    - typing-extensions >=4.12
    - tomli

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  requires:
    - pip
  commands:
    - alembic --help
    - pip check

about:
  home: https://github.com/sqlalchemy/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  description: Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: https://alembic.sqlalchemy.org

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
