{% set name = "alembic" %}
{% set version = "1.2.1" %}
{% set hash_type = "sha256" %}
{% set hash = "9f907d7e8b286a1cfb22db9084f9ce4fde7ad7956bb496dc7c952e10ac90e36a" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - alembic = alembic.config:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy >=1.1.0
    - mako
    - python-editor >=0.3
    - python-dateutil

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util

  commands:
    - alembic --help

about:
  home: https://bitbucket.org/zzzeek/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'A database migration tool for SQLAlchemy.'
  dev_url: https://bitbucket.org/zzzeek/alembic
  doc_url: http://alembic.zzzcomputing.com/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
