{% set name = "alembic" %}
{% set version = "1.7.5" %}
{% set hash = "7c328694a2e68f03ee971e63c3bd885846470373a5b532cf2c9f1601c413b153" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - alembic = alembic.config:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - mako
    - sqlalchemy >=1.3.0
    - importlib-metadata  # [py<39]
    - importlib_resources  # [py<39]
    # Optional dependencies
    - python-dateutil

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.operations
    - alembic.runtime
    - alembic.script
    - alembic.util
  requires:
    - pip
    - python <3.10
  commands:
    - alembic --help
    - pip check

about:
  home: https://github.com/sqlalchemy/alembic
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: https://alembic.sqlalchemy.org/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
