{% set name = "alembic" %}
{% set version = "1.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c3ddb635f26efbc80b1b90c5652548202022d4e760f6a78d6d85959280e3684

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - alembic = alembic.config:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python
    - mako
    - sqlalchemy >=1.4.0
    - typing-extensions >=4.12
    - tomli  # [py<311]
    - typing_extensions >=4.12

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.autogenerate.compare
    - alembic.config
    - alembic.ddl
    - alembic.environment
    - alembic.migration
    - alembic.operations
    - alembic.operations.base
    - alembic.operations.batch
    - alembic.runtime
    - alembic.runtime.migration
    - alembic.script
    - alembic.script.revision
    - alembic.util
    - alembic.util.messaging
    - alembic.util.sqla_compat
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - alembic --help
  # Upstream tests based on database connection
  requires:
    - pip

about:
  home: https://alembic.sqlalchemy.org
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A database migration tool for SQLAlchemy.
  description: Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python.
  dev_url: https://github.com/sqlalchemy/alembic
  doc_url: https://alembic.sqlalchemy.org

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - xylar
