travis:
  secure:
    BINSTAR_TOKEN: Ovs3Ky00b88vTRUJQDVioETmCxNseHBXXxfyobM+Q/uIIemdHm56ynRsGfiQyDfI3+vooXKRUBYWHxUnIN96Lnb5FCOG68sEnclIvZrkymU8FOa6CvlLI5ZEFDnbv5uWb6fpJ6UWKqEgFawLznR9Yn+/u46CGeCLFkhXaK7zZ90D8DvdOZ2ULZ0uBLMW2VHG9SfBIQNh2maP7K0sVYDGZPAME5Kv0iLLIKB/kAi6m4mHgopBWlSqr35G/nsywJcbT/rXmPO+8ZHbx2PbW8XfksOG8c/6gtfUc84fabYamgweS42NCSR+/1MD0RsZxTTC8LeBbiuTMg1bPZe8vtSb0aiAA+6XYqTIBweww3OEBpQ5JMRJrvkBT4XUpJI5StrOUVywG2Vyycv7ITk/46SDm0JqDOH7GtcjIydpuT2bEhrHTUcBG1VygnfbNKYgkxhumZJhfl2BbCajFCQCzHdHkTf4eQ+VpJLqtIQyJ5dwOOBhqHsYA62r0/hcydF1xlfW+F0VupuM3Mh9L4ska9iWu4crQ9XKnzUR52dfrn863QUqxttfB78jznB+HMO7aPJUqtgFOE+Z5P6hdNYuBptDFjF2tNxlSwgqQyWGFk8u3REJFH9CgN0O8Ty5n7gFawDJ+xX1zd2YGxE/QjN7+WX3A5EgeglerPEG0MTMUnqvLY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
