travis:
  secure:
    BINSTAR_TOKEN: uB7XzD9D6fMYQZE5mShsWliMZQ7sx6FZhvzPeW2ZS/anQIxm3G4r2YNCbHMXfkOC7c+nr1DW/xD267VvP4apUqHkP1BOxjexQWuXbp1KrN1e5+bvoeG/QuZaf4HQssVDh91xLJUjho4Svs9rxO21/G5Ay0jJKpgosSA2cweO5jzcex6taVwuXKZYRk2tYOHgt+TGRCNqCI5eHT+zVqh3A3PIMlqKSeCzBDP6DZsKtsBr2UMEashaFYkaVBxRTKmqS/nXNh0VNtuClJUYutInjmyjOOdAMsZhmMAwJL5QUuzbk/9qf2cQXUKFib5VZeOomPWjXlk4snBFCGxaZiax2YUQrBJ1xksuQqIydCuXyf1U4iDzKR6mq0Vb6tjrubafDd3Xpkisf2ZwRvHQf0oisZvXhqSumFpabT2nZAA5+Xbak31JZsBMKNVkA9iDXYfMObyVBMpBa6YIrOBvYuwn1Zv5sBCernz2Z+r72l5mE19Yz1BL25h0qnqTxgQjAH0a77HrYlVQ46nOrKOYvl5DRDv7LiyJxbLIUNuLqGjPLhOXxN51Ns2RZpdndntGVioXX2m/yXrqL66aJ7tTcyey0vWpDgyi0SLvHfCtHDWg5X4CybkA0mTCgoeVlS/mwtPtWlvhaTRyg44bFggxwUWWa491kcKm+9kJsA57EKyfAmI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
