travis:
  secure:
    BINSTAR_TOKEN: g5U9Utq3CjZ6iiRHmJDFBOzEsNWUotKPNX8YBwnSFgF+DkXt3X75OkfkroIj4Nq6UhHDXcWCSxX8pa+2Jdw+s2GmaR+lDaoJew9ZSSkmDYJFhuAwUAastUjDmI82aIFALb7PbqhPnzsAZYAaxFnqQDebViSusEE1bE2zMadVSFuiNcXQ3C/78sqn4G3B3U7p/ApJ5Q9G+sIj16vZU9NiT4Exa4/fT+w6zGTUI+aDvxg9B9qynTdXqUlplgtasbc9xcLiVJa1tvZA+1koB0L5hrqjtHW+ohNxJkgIzuuqw5y+yHMNO8uMF0NWNtgMUSMBX35Z/L9RES7mNh6h4onYwDEfTDJmYISJy/xvu5aBXVDJA02nUqSP68sc1SWaeV6TOEDTmfBi9wva0BMaZ79xtOp7zxJGy1nSEbC72vx7S3OZEXzF1fmrrqys5yTrgj6yiLkq3eMtccbgOidhd6LgLZUGhCJ7tdxX40CzWn65nvw5OdTySqmyhK+D+wvY3+uEQIYTb//zvuMqf1Ta+jDQl7qvYFhvDZ75WfP1oYyDrpPN0u811uHIPkmfcFOmdcFDs8CrHwr+CmYi9UPmp5dH1naojWekFXBSUkSl1pVyVMY09fk+BYyttL2uNo2yqkkar63299ncunjajtoykjVgtxUcLc+iYN+mZab4a+OWm5o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
